// Chữ dùng chung trên web. Mỗi dòng là một nội dung có thể sửa.
export default {
  latestTitle: "Mới phát hành",
  latestBadge: "Mới nhất",
  preview: "Xem trước",
  download: "Tải",
  openThemeApp: "Mở Chủ đề",
  loadingDownloads: "Đang lấy lượt tải...",
  downloads: "lượt tải",
  currentVersion: "Phiên bản hiện tại",
  latestStatus: "Mới nhất",
  donateTitle: "Ủng hộ dự án",
  donateHint: "Quét mã để chuyển khoản",
  accountOwner: "Chủ tài khoản",
  accountNumber: "Số tài khoản",
  copyHint: "Chạm để sao chép",
  thankYou: "Mỗi lượt ủng hộ đều giúp dự án được duy trì và cập nhật tốt hơn. Cảm ơn bạn!",
  donorsTitle: "Những người đã ủng hộ",
  donorsLabel: "người ủng hộ",
  donorsSubtitle: "Từng đóng góp đều đáng quý",
  emptyDonors: "Danh sách người ủng hộ sẽ xuất hiện tại đây.",
  readGuide: "Đọc hướng dẫn",
  watchVideo: "Xem video",
  footer: "Copyright © 2026 DTINH. All rights reserved."
};
